name: cream contract test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v1

    - name: Setup node-version ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
        registry-url: 'https://registry.npmjs.org'
        
    - name: Install and prepare
      run: |
        npm install -g yarn
        npm install -g lerna
        lerna bootstrap -- --ignore-engines
        lerna run build
        ./packages/circuits/scripts/installZkutil.sh
        
    - name: Test
      env:
        NODE_OPTIONS: --experimental-worker
      run: |
        yarn test
